### ISSUE TITLE
output JSON to stdout

### ISSUE THREAD

**Issue by kelvinabrokwa** [wm-robo-ops/TSP#1]
Easier to consume for whatever process calls this on the server

**Comment by ajwells** [comment]
checkout master branch for a manual JSON output example:

{
        "nodes":
                [
                        { "lat": "38.9047", "lon": "77.0164", "color": "bidDaddy" },
                        { "lat": "37.2711", "lon": "76.7075", "color": "yellow" },
                        { "lat": "29.7604", "lon": "95.3698", "color": "green" },
                        { "lat": "37.5333", "lon": "77.4667", "color": "kosmo" }
                ],
        "distance": "2.17321e+006",
        "points": "0"
}

**Comment by kelvinabrokwa** [comment]
@ajwells that looks great! I think we can close this.
